require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - lib/onlyoffice_webdriver_wrapper/helpers/headless_helper/headless_patch.rb

Naming/PredicateMethod:
  Enabled: false
