name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2']
        allow-failures: [false]
        include:
          - ruby: head
            allow-failures: true
    steps:
      - uses: actions/checkout@v2
      - name: Update to current stable google-chrome
        run: |
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_112.0.5615.121-1_amd64.deb"
          sudo dpkg -i ./google-chrome-stable_112.0.5615.121-1_amd64.deb
      - name: Install dependencies
        run: sudo apt -y install ffmpeg
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
